### ISSUE TITLE
Migrate non core opentelemetry-ruby components to opentelemetry-ruby-contrib

### ISSUE THREAD

**Issue by ericmustin** [open-telemetry/opentelemetry-ruby-contrib#1]
Placeholder for @ericmustin @arielvalentin to determine a strategy for migrating the relevant portions of https://github.com/open-telemetry/opentelemetry-ruby into this repository

**Comment by ericmustin** [comment]
@arielvalentin and I met, some mtg notes:

### Summary

#### Open Questions

- right now the sdk has a dependancy on base, due to `Opentelemetry::Instrumentation.registry`. 
  -  where does the specification say this should live, or where should this actually be?
  - where should registry live.
  - whats in spec? Is this specified anywhere or is it just the otel-ruby convention.
  - whats the fastest path for us to get this out the door?

- .toys, .github workflows and release directory questions
  - specifically, the rubygems_api_key, is that org wide or a personal token? Who owns it, is it org wide, repo wide, etc?
  - do we need to copy or bring this over to -contrib ? What do we need to delete in current -core .toys folder?
  - we dont have access to any secret setting in GH, how can we set the rubygems api key so we can release from contrib

#### Moving List

- to move:
  - `.instrumentation_generator`: all
  - `.toys/.github` tbd see above Q
  - `instrumentation`: all
  - `propagator`: ottrace+xray
  - `rakelib`: update_registry_instrumentations - tbd lets figure out if we should just dupe this or how it's used
  - `resource_detectors`: all
  - `bin`: all
  - misc: gemfile/rakefile/readme/.gitignore/docker/various.md and docker files

### Misc

- talk to appropriate stakeholders on above open questions

**Comment by mwear** [comment]
I can give some more information on a couple of the open questions.

Opentelemetry::Instrumentation.registry is something introduced by OpenTelemetry Ruby. There is no formal spec for it. It can live wherever is most convenient.

The ruby gems api key is tied to our rubygems account. The email for the account is a cncf mailing list with that includes the maintainers. We will need to port this over to contrib. I believe @dazuma originally set this up on the main repo. Perhaps he can help with contrib, or advise us on how to copy it over.

**Comment by arielvalentin** [comment]
@mwear Neither @ericmustin or I have access to customize this repository e.g. Setting Actions Secrets or configuring branch protection rules. 

Do you happen to know what we would need to do to gain access to those features?

**Comment by mwear** [comment]
@arielvalentin I've updated your permissions (and the other contrib maintainers). Let me know if that does the trick.

**Comment by arielvalentin** [comment]
@plantfansam Here is a rough layout of the tasks that we discussed yesterday:

- [ ] Remove all references to local paths in api, sdk, otlp-exporter, metrics, and propagators in the Gemfiles
- [ ] Delete appraisal generated gemfiles. We will generate them as part of the CI build
- [ ] Update Instrumentation Base to depend on the Registry gem. Delete duplicate Registry in Base
- [ ] Replace SDK Dependency in Base with Registry
- [ ] Prune any files that will remain in the main repo and force push into the contrib repo
- [ ] Test releasing gems from contrib
- [ ] Prune files that were relocated here from the main repo
- [ ] Setup `CODEOWNERS` for existing instrumentations outside of @open-telemetry/ruby-contrib-maintainers e.g. Aspect.io for AWS

I plan on submitting multiple PRs to update each subset of features. The first set of dependencies I am working on is the instrumentations. LMK if you are available to help out with anything else. 

cc: @chrisholmes :)

**Comment by chrisholmes** [comment]
I'm available to help. Is there anything independent enough that I can pick up?

**Comment by arielvalentin** [comment]
@chrisholmes thank you for answering the call! I think having your help on the RSpec instrumentation test suite is going to be a big help for us and if it is OK with you I will add you as one of the codeowners for that instrumentation when we move it along. Would you be amenable to that?

I have opened PRs for the completed tasks above and I think that the rest of the tasks must be done serially. If you have some time to take a look at them and provide feedback that would be a great help to me (commenting is fine no ✅ required)

- https://github.com/open-telemetry/opentelemetry-ruby/pull/1222
- https://github.com/open-telemetry/opentelemetry-ruby/pull/1221
- https://github.com/open-telemetry/opentelemetry-ruby/pull/1220

I have also run into some non-deterministic tests along the way causing me to rebuild multiple times. If you run into one of these tests please let us know and I would appreciate your help tracking down the root cause and fixing the test.

Another thing you may be able to help us with is testing releases. Right now everything is released from this repository but when it is time for us to move it we need to ensure we are able to properly release gems and that you are able to upgrade your applications without any issues.

**Comment by chrisholmes** [comment]
> @chrisholmes thank you for answering the call! I think having your help on the RSpec instrumentation test suite is going to be a big help for us and if it is OK with you I will add you as one of the codeowners for that instrumentation when we move it along. Would you be amenable to that?

I'm onboard with that @arielvalentin. I'm also happy to help with other instrumentation gems if you'd like additional support.

**Comment by arielvalentin** [comment]
@chrisholmes wonderful! Thanks again for your support and contributions.

**Comment by arielvalentin** [comment]
We will lose pull request links and relevant build history. Commit history is preserved. 

<img width="1523" alt="2022-05-21_09-45-55" src="https://user-images.githubusercontent.com/82798/169656778-60241bcb-2348-455e-91c4-e203a495507c.png">

<img width="1543" alt="2022-05-21_09-43-19" src="https://user-images.githubusercontent.com/82798/169656699-96e8c3e3-87d7-4eb2-a820-018fa3015ff3.png">
