### ISSUE TITLE
Codify policy for which versions of instrumented gems we support

### ISSUE THREAD

**Issue by plantfansam** [open-telemetry/opentelemetry-ruby-contrib#103]
We should have a policy stating which versions of an instrumented gem (e.g. `pg`) will be supported by this repo's instrumentation gem (e.g. `opentelemetry-instrumentation-pg`). We set constraints in each gem's `compatible` block, but as far as I know this compatibility doesn't derive from a published policy.

Since we are often monkey-patching private APIs, we may not be able to derive a sensible policy from the instrumented gem's semver. Or if we do derive the policy from semver, we might need to commit to monkey-patching the same method a couple different ways, depending on the version of the gem being instrumented.

We may need to update the as-yet-nonexistent [style guide](https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/68) if we choose to make this policy ("no conditionals based on the instrumented gem's version" or "use `OpenTelemetry::Common.gem_version(3.0) do` when targeting specific underlying gem version").

@open-telemetry/ruby-approvers @open-telemetry/ruby-maintainers — any thoughts here?

**Comment by ahayworth** [comment]
I think my main thought here is: "it may be hard to derive a single, consistent policy". Not to say we shouldn't try, though.

One possibility might be to say "we will generally support the last 3 major releases of a library we instrument, unless there is compelling reason to do otherwise."

Another possibility could be "we will support the 3 most popular versions of a gem, as determined by <some method that I bet @robbkidd could whip up>".

Or maybe some combination.

**Comment by arielvalentin** [comment]
@ericmustin @mwear @robertlaurin @robbkidd @ahayworth discussed this again during the sig on 2022-10-18 

- Instrumentation authors should attempt to implement 1st Party instrumentation and fall back to this repository  
- New instrumentations require a commitment from the author to review and maintain releases
- We will add the instrumentation author to the `CODEOWNERS`[^1] file for that instrumentation so they are notified when a PR is submitted for that instrumentation
- The @open-telemetry/ruby-contrib-maintainers reserve the right to deprecate any unmaintained instrumentation, i.e. any instrumentation where the author is unable to provide fixes, updates, etc... in X number of days.
- We will declare Truffle, windows, and Mac OS as experimental platforms and remove them from our primary matrix builds. @ericmustin suggested that we move these platforms and runtimes to a canary build that runs nightly. @robbkidd and I will collect usage data via Honeycomb RubyGems reports.  

[^1]: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by ahayworth** [comment]
> Instrumentation authors should attempt to implement 1st Party instrumentation and fall back to this repository

That's a laudable goal, but it feels like it may have been outside the scope of this issue. Given that we do not have any first party instrumentation yet, I'm not sure that this is going to be workable in practice. I would feel better if we had some examples of this approach succeeding in the ruby community before declaring it policy in this repo.

> New instrumentations require a commitment from the author to review and maintain releases

Were we having significant difficulty with this already? I find myself wondering what the motivation was here, and if we should make sure to spell out and address the underlying concerns explicitly.

---

I suppose I'm not strictly opposed to what you are proposing in this comment but it's definitely surprising to see it spelled out this way, in this context. Deprecating jruby, for instance, is a big decision.

Should we step back and discuss these separately?

**Comment by arielvalentin** [comment]
> That's a laudable goal, but it feels like it may have been outside the scope of this issue. Given that we do not have any first party instrumentation yet, I'm not sure that this is going to be workable in practice. I would feel better if we had some examples of this approach succeeding in the ruby community before declaring it policy in this repo.

Yes it is. I think we can start by setting an example and reach out to gem authors of our current instrumentations  

> Were we having significant difficulty with this already? I find myself wondering what the motivation was here, and if we should make sure to spell out and address the underlying concerns explicitly.

Any amount of friction for me is already too much friction. 

We kept EoL versions for AWS SDK expecting commitment from the instrumentation authors but they have stopped development and collaborating on the project. There are also incomplete features such as extracting context propagation from SQS. 

`rdkafka` is constantly segfaulting and we don't have any capacity to investigate. 

We have an EoL Rails coming up 6.0 and we should keep up with dropping support otherwise we get stuck maintaining compatibility with versions.  

> I suppose I'm not strictly opposed to what you are proposing in this comment but it's definitely surprising to see it spelled out this way, in this context. Deprecating jruby, for instance, is a big decision.

Based on the data we queries in Honeycomb RubyGems dashboard and my personal desire/capacity, these are the platform that I propose we target for our Main CI/Release Process:
 
- Linux 
- Yarv/MRI Ruby
- JRuby

These are the experimental platforms that need dedicated maintainers and will therefore not block releasing new versions of instrumentations:

- Mac OS
- Windows 
- Truffle

**Comment by plantfansam** [comment]
I don't have a ton to add here, except that:

a) I (strongly) agree we should push for first-party instrumentation where possible.
b) We should find some candidate gem(s) to add first-party instrumentation to, demonstrate the viability of this strategy, and then write something up explaining how easy it is. Concurrent-ruby is potentially a good candidate.
c) I fully support moving macos, windows, and truffle to a nightly canary build that won't block releases

**Comment by ahayworth** [comment]
> moving macos, windows, and truffle to a nightly canary build that won't block releases

#172 will do that, and yeah those platforms seem definitely fine to me to move to a canary build.
