### ISSUE TITLE
How to handle gRPC repo w.r.t. attribution/licensing

### ISSUE THREAD

**Issue by hibachrach** [open-telemetry/opentelemetry-ruby-contrib#1041]
Hello,

I recently created [`opentelemetry-instrumentation-grpc`](https://github.com/hibachrach/opentelemetry-instrumentation-grpc) (Ruby gem forthcoming) which is mostly just a fork of much of the [`opentelemetry-instrumentation-gruf`](https://github.com/open-telemetry/opentelemetry-ruby-contrib/tree/main/instrumentation/gruf) code.

I had a few questions:
- How would folks prefer attribution to be given?
- I didn't preserve the copyright notices at the top of the files as it's not in the open-telemetry org. That said, I'm happy to restore them should that be preferred--I'm not sure what the policy is w.r.t. in-code copyright notices & forking
- Is my choice of MIT license acceptable? Or does it need to maintain the same license as in this repo (Apache 2 IIRC)?

I would have opened a PR to just add the code to this repo but I wasn't sure if I could commit to maintaining it (which the contributing guidelines request).

Thank you!

**Comment by kaylareopelle** [comment]
Hi @hibachrach! Thank you for these questions!

I'm really not sure what the answers are and will bring them up in our next SIG meeting. 

If you'd like to join the meeting to be part of the discussion, [here's a link to our Google Group](https://groups.google.com/a/opentelemetry.io/g/calendar-ruby), and the calendar invite should be sent to you after you join. 

We meet Tuesdays at 9:00AM PT.

**Comment by kaylareopelle** [comment]
Hi @hibachrach, 

First off, thank you for building this gem! gRPC instrumentation has been wanted for a long time (see https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/10), and I'm excited to see it come together.  

We talked about your questions during the SIG yesterday and would like to welcome the gem into the `opentelemetry-ruby-contrib` repo, even if you're unable to meet the maintaining commitments outlined in the contributing guidelines.

Is there any level of engagement you'd be willing to commit to? Are there specific requirements you feel uncomfortable about fulfilling? (We're fine either way, and looking for feedback since these guidelines are relatively new)

Despite our preference to bring `opentelemetry-instrumentation-grpc` into `opentelemetry-ruby-contrib`, this is not an obligation. 

If you'd prefer to keep the gem separate, we understand that too.

To answer your questions, the safest legal path would be to retain the Apache 2.0 license, keep the license headers, and add your additional copyrights to the headers on the files you modified.   

There is also an Apache 2 NOTICE file you could use as well. [Here's an example from apache httpd](https://svn.apache.org/viewvc/httpd/httpd/trunk/NOTICE?view=markup), and [here's a file with retained copyright](https://svn.apache.org/viewvc/httpd/httpd/trunk/support/firehose.c?view=markup). 

Google Open Source has some additional recommendations on this topic: https://opensource.google/documentation/reference/copyright#files_derived_from_third_party_code

**Comment by hibachrach** [comment]
> First off, thank you for building this gem! gRPC instrumentation has been wanted for a long time (see https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/10), and I'm excited to see it come together.

Happy to help in any small way I can 😄

> Is there any level of engagement you'd be willing to commit to? Are there specific requirements you feel uncomfortable about fulfilling? (We're fine either way, and looking for feedback since these guidelines are relatively new)

I'm happy to try to help to the extent that I'm able with bugs but I only incidentally work with this code as it pertains to my company's system. I also know I get burnt out doing dev work in my free time when it's my primary job at work so I don't want to say one thing and do another. I can therefore commit primarily to trying, lol.

**Comment by kaylareopelle** [comment]
Great! Thank you so much! 

> I'm happy to try to help to the extent that I'm able with bugs...

That makes a lot of sense. Committing to trying works for me! 😄

**Comment by kaylareopelle** [comment]
Hi @hibachrach! Checking back in on this! Anything we can do to help?

**Comment by hibachrach** [comment]
Hey sorry, have just had a busy personal life recently. Going to take a look at this this weekend.
