### ISSUE TITLE
PG does not support enabled

### ISSUE THREAD

**Issue by zrzka** [open-telemetry/opentelemetry-ruby-contrib#1095]
**Description of the bug**

[This page](https://opentelemetry.io/docs/languages/ruby/libraries/#overriding-configuration-for-specific-instrumentation-libraries) says the following:

> For example, here’s how you can install all instrumentations except the Redis instrumentation into your app:
>
> ```
> ...
> config = {
>   'OpenTelemetry::Instrumentation::Redis' => {
>     enabled: false
>   }
> }
> c.use_all(config)
> ...
> ```

One can think that all libraries can do this. I've tried it with the `PG` one, and it yields:

```
ignored the following unknown configuration options [:enabled]
failed to install
```

Using:

- opentelemetry-sdk 1.4.1
- opentelemetry-instrumentation-base 0.22.4
- opentelemetry-instrumentation-pg 0.27.3

There're new versions available. Did check history / changelogs, and didn't find anything `enabled` related.

Is this supposed to work in all instrumentation libraries?

**Comment by xuan-cao-swi** [comment]
Hi, thanks for reporting the issue. I think this `ignored the following unknown configuration options [:enabled]` is a confusing log message and shouldn't be there; and I think it's happening to all instrumentation libraries.

In fact, when you pass `'OpenTelemetry::Instrumentation:: PG' => { enabled: false }` in config, the PG is indeed disabled.

**Comment by zrzka** [comment]
Isn't it disabled because of the 2nd log line which says `failed to install`? IOW, coincidentally because of the 1st one?

**Comment by xuan-cao-swi** [comment]
It failed to install not because of 1st one (assume you are referring to the first log msg); it failed to install because of the config `{ enabled: false }`. 

If you try `'OpenTelemetry::Instrumentation:: PG' => { enabled: true }`, it will show successfully installed, but the log `ignored the following unknown configuration options [:enabled]` will still appear.

Anyway, `ignored the following unknown configuration options [:enabled]` doesn't mean anything for option `:enabled`, you can just ignore it for now.
