### ISSUE TITLE
Active Record Fails because of an unexpected arguments in find_or_create_by function

### ISSUE THREAD

**Issue by tomerfriedman** [open-telemetry/opentelemetry-ruby-contrib#268]
Could not initialize ActiveRecord because of an unexpected error that is thrown and crashs my app.

**Share details about your runtime**

RUBY_ENGINE: "ruby"
RAILS: "6.0.4.7"

Getting the following error on "find_or_create_by" function:

```
wrong number of arguments (given 2, expected 0..1)
```

Attached picture:

<img width="950" alt="image (16)" src="https://user-images.githubusercontent.com/79840387/211616208-2848e5a2-29aa-40bf-a002-73cbbf94ffab.png">

**Comment by arielvalentin** [comment]
Thanks for reporting this issue. This is an issue with the protected_attributes_extended gem overriding and changing ActiveRecord Persistence create signature.

The original Rails create method only accepts a single attributes hash argument:

https://github.com/rails/rails/blob/main/activerecord/lib/active_record/persistence.rb#L33

However the protected_attributes gem _redefines_ the method signature and changes it to accept multiple hash arguments:

https://github.com/westonganger/protected_attributes_continued/blob/master/lib/active_record/mass_assignment_security/persistence.rb#L41

The OTel Instrumentation _preserves_ the method signature when it adds the tracing functionality  

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/patches/persistence_class_methods.rb#L21

During initialization time, the protected attributes gem is mixed in, which adds the parameter, then the OTel instrumentation is mixed and _reverts_ the signature back. 

Then when your code runs... :bomb: `ArgumentError`.


I'd argue here that this isn't a bug with the instrumentation but rather with protected attributes because it should not change ActiveRecords public API. 

To get your app working again using OTel I recommend that you disable the AR instrumentation but I think that ultimately this should be something that needs to be fixed in the protected attributes gem. 

Disabling AR instrumentation  should still give you some useful traces. 

HTH
