### ISSUE TITLE
OTTrace trace ID seem to require 32 char instead of 16

### ISSUE THREAD

**Issue by kamal** [open-telemetry/opentelemetry-ruby-contrib#521]
The documentation for the OTTrace propagator mentions that the traceid header is required and should be a uint64 encoded as a string of 16 hex characters.

The implementation however seems to require a 32 char hex string?

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/1990634acece4b32f56663a720e18b27a14a2b25/propagator/ottrace/lib/opentelemetry/propagator/ottrace/text_map_propagator.rb#L21

**Comment by arielvalentin** [comment]
I think our documentation could be a bit more clear in this case. 

The reason the regexp validates a 32 char string is because it is comparing it to a normalized 16 byte array converted to hex digits to make sure it is compatible with the W3 Trace Context format, i.e. 16 bytes == 128 bits == 32 hex digits 

A little background on this...

OTTrace was changed to be interoperable with other format so it is supposed to 8 or 16 byte array values for the trace-id. 
In order to do that Lightstep released a version of the OTTrace propagators that left padded 8 byte headers to 16 bytes using an additional 8 bytes of `0`s. 

The reality of the world is not every application upgraded to support 16 byte array propagation format, but this propagator must still convert legacy 8 byte trace ids to match the [W3C Trace Context Trace ID](https://www.w3.org/TR/trace-context/#trace-id) 16 byte array. 

In addition to that it must be interoperable with legacy OTTracers, which expect 8 byte headers so this propagator truncates the value from a 16 byte array to an 8 byte array value before inject it into the carrier. 

So this propagator is compatible with 8 or 16 byte trace ids which it normalizes to 16 bytes but only emits 8 byte trace ids.

Hope that helps.
