### ISSUE TITLE
Rails Data Export

### ISSUE THREAD

**Issue by leoluchini** [open-telemetry/opentelemetry-ruby-contrib#832]
Hi everyone,

I'm currently working on implementing `opentelemetry-instrumentation-rails ~> 0.30`, and while it is functional, I would like to modify the way the data is exported.

Currently, when I check the dashboard with the data, it is grouped by controller name and action, as shown in the attached screenshot:

![Screenshot 2024-01-22 at 09 08 27](https://github.com/open-telemetry/opentelemetry-ruby/assets/5969628/9b84f67d-27ff-4662-bdbd-f014653ff9d5)
 This is the trace 
![Screenshot 2024-01-22 at 09 09 51](https://github.com/open-telemetry/opentelemetry-ruby/assets/5969628/70dadecf-fe69-416d-b419-402bc268ccd6)

My current configuration is

```
OpenTelemetry::SDK.configure do |c|
  c.service_name = ENV.fetch('OTEL_SERVICE_NAME')
  c.use_all( {'OpenTelemetry::Instrumentation::Rack' => { url_quantization: lambda { |path, _env|  path.to_s } }})
end
```

Instead of displaying the controller name and action, I would prefer to have the HTTP action and the path, such as GET /ping. Is this customization possible? Any assistance would be greatly appreciated.

Feel free to let me know if you have any specific preferences or if there are additional details you'd like to include in the message.

**Comment by arielvalentin** [comment]
Thanks again for reporting this issue. 

I see here that the span name is being rewritten and I see why this is causing trouble for you, especially since it is not well documented. 

Here is where the span name is being overridden and ignoring quantized span names:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/f5f21c686aa8b463a2fb6edd39260cf2a7da7043/instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/handlers/action_controller.rb#L29

This is not compliant with the specification either so I think this needs to change but I think I need to discuss this with other maintainers today at the SIG and see what we think is the best direction to go here. When I have those details I will update this issue. 

You will have to manually overwrite the span name in custom code as part of ActionController Base for now until we address this issue.
