### ISSUE TITLE
RubyGem Documentation Hosting

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#99]
Any gems published from this repository are available on rubydoc.info[^1] as well as a custom GitHub Pages Site[^2]. 

Is there an advantage to hosting the documentation on a GH Pages Site over using rubydoc.info? 

The source of the GitHub pages site is found here: https://github.com/open-telemetry/opentelemetry-ruby-contrib/tree/gh-pages

The GitHub pages site is updated as part of the release process: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/.toys/release/.lib/release_performer.rb#L156

cc: @open-telemetry/ruby-maintainers

[^1]: https://www.rubydoc.info/find/gems?q=opentelemetry-instrumentation
[^2]: https://open-telemetry.github.io/opentelemetry-ruby-contrib/

**Comment by ahayworth** [comment]
Personally I have run across times when `rubydoc.info` is slow, but I don't think I would block on that myself (it's usually fine, and it's where I would expect docs to be).

That said, I did have a heck of a time getting to any ruby documentation when I was at the airport the other day: https://twitter.com/drewbug01/status/1543293095281827843 ... so that may be one reason to keep our own site up. But a minor one, again.

Reducing duplication is probably a bigger win.
